/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.starbug1.android.newsapp.utils;

import java.lang.reflect.Field;

import com.starbug1.android.newsapp.AppException;

import android.content.Context;
import android.util.Log;

/**
 * リソースクラスへのプロキシ
 * @author smeghead
 *
 * 通常、自動生成されるRクラスから参照したIDを使って、layoutファイルなどの情報にアクセスする。
 * 複数プロジェクトから共通で利用したい機能を実装する際に、自動生成されたRクラスに直接アクセスしていると
 * そのまま再利用できなくなる。
 * 
 * それを解決するために、複数プロジェクトから共通で利用したい機能では、ResourceProxy.R を経由して
 * IDを参照する。
 * ResourceProxy.R にアクセスする前に、ResourceProxy.Rの各値は、それぞれのプロジェクトで自動生成された
 * IDで、初期化される必要がある。
 * ResourceProxy.R.init(project.package.R.class); 
 */
public final class ResourceProxy {
	private static final String TAG = "ResourceProxy";
	
	
	// 以下のクラスを経由して、自動生成されたクラスにアクセスする。
	public static final class R {
		public static void init(Context context) {
			try {
				String className = context.getPackageName() + ".R";
				init(Class.forName(className));
			} catch (Exception e) {
				Log.e(TAG, e.toString());
				throw new AppException("no class definetion. needs R class update?");
			}
		}
		
		public static void init(Class<?> resourceClass) {
			try {
				for (Class<?> c : resourceClass.getClasses()) {
					Class<?> clazz = getClassByName(R.class, c.getName());
					for (Field f : c.getDeclaredFields()) {
//						Log.d(TAG, c.getName() + "." + f.getName() + ": " + f.get(null));
						clazz.getField(f.getName()).set(null, f.get(null));
					}
				}
			} catch (Exception e) {
				Log.e(TAG, e.toString());
				throw new AppException("no class definetion. needs R class update?");
			}
		}

		private static Class<?> getClassByName(Class<?> clazz, String name) {
			name = name.replaceFirst(".*\\$", "");
			for (Class<?> c : clazz.getClasses()) {
				String n = c.getName().substring(clazz.getName().length() + "$".length());
				if (name.equals(n)) {
					return c;
				}
			}
			throw new AppException("no class definetion. needs R class update?");
		}
		
		public static final class animator {
	        public static int left_in=0x7f040000;
	        public static int left_out=0x7f040001;
	        public static int right_in=0x7f040002;
	        public static int right_out=0x7f040003;
	    }
	    public static final class array {
	        public static int arrays_entry_action_values=0x7f060003;
	        public static int arrays_entry_actions=0x7f060002;
	        public static int arrays_pref_interval_values=0x7f060001;
	        public static int arrays_pref_intervals=0x7f060000;
	        public static int arrays_mobile_url_orgin=0x7f060004;
	        public static int arrays_mobile_url_repleace=0x7f060005;
	    }
	    public static final class attr {
	    }
	    public static final class drawable {
	        public static int header=0x7f020000;
	        public static int ic_menu_dialog=0x7f020001;
	        public static int ic_menu_globe=0x7f020002;
	        public static int icon=0x7f020003;
	        public static int loading=0x7f020004;
	        public static int newentry=0x7f020005;
	        public static int no_image=0x7f020006;
	        public static int notify=0x7f020007;
	    }
	    public static final class id {
	        public static int adView=0x7f0a000f;
	        public static int adView2=0x7f0a0005;
	        public static int entryView=0x7f0a0002;
	        public static int favorite=0x7f0a0014;
	        public static int favorite_blocks=0x7f0a000d;
	        public static int grid=0x7f0a0008;
	        public static int header=0x7f0a000a;
	        public static int imageView1=0x7f0a0000;
	        public static int image_share=0x7f0a0003;
	        public static int initialMessage=0x7f0a0015;
	        public static int item_container=0x7f0a0010;
	        public static int item_image=0x7f0a0011;
	        public static int item_title=0x7f0a0012;
	        public static int linearLayout1=0x7f0a000b;
	        public static int main_view=0x7f0a0009;
	        public static int menu_all=0x7f0a001d;
	        public static int menu_favorite=0x7f0a0018;
	        public static int menu_favorites=0x7f0a0020;
	        public static int menu_notify_all=0x7f0a001b;
	        public static int menu_other=0x7f0a0019;
	        public static int menu_reload=0x7f0a0016;
	        public static int menu_review=0x7f0a001a;
	        public static int menu_settings=0x7f0a001f;
	        public static int menu_share=0x7f0a0017;
	        public static int menu_support=0x7f0a001c;
	        public static int menu_update_feeds=0x7f0a001e;
	        public static int month=0x7f0a0007;
	        public static int month_container=0x7f0a0006;
	        public static int newEntry=0x7f0a0013;
	        public static int no_favorites_message=0x7f0a000c;
	        public static int relativeLayout1=0x7f0a000e;
	        public static int relativeLayout2=0x7f0a0004;
	        public static int version=0x7f0a0001;
	    }
	    public static final class layout {
	        public static int entry=0x7f030000;
	        public static int favorite_block=0x7f030001;
	        public static int favorite_list=0x7f030002;
	        public static int item_row=0x7f030003;
	        public static int main=0x7f030004;
	        public static int pref=0x7f030005;
	    }
	    public static final class menu {
	        public static int entrymenu=0x7f090000;
	        public static int favoritesmenu=0x7f090001;
	        public static int mainmenu=0x7f090002;
	    }
	    public static final class string {
	        public static int app_name=0x7f070001;
	        public static int hello=0x7f070000;
	        public static int initial_message=0x7f070003;
	        public static int no_favorites_message=0x7f070004;
	        public static int shareDescription=0x7f070002;
	    }
	    public static final class style {
	        /**  
		    <item name="android:windowFrame">@drawable/screen_frame</item>
			
		    <item name="android:windowBackground">@drawable/screen_background_white</item>
		    http://www.techdoctranslator.com/android/guide/ui/themes
	 
	        <item name="android:textColor">#000000</item>
	        <item name="android:background">#ffffff</item>
	         <item name="android:typeface">monospace</item> 
	         */
	        public static int CustomTheme=0x7f080000;
	        public static int appLayout=0x7f080001;
	        public static int appPrefItem=0x7f080002;
	    }
	    public static final class xml {
	        public static int pref=0x7f050000;
	    }
	}
}
